
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pcris
 */
public class RegistarEntidades extends javax.swing.JInternalFrame {

    /**
     * Creates new form Categoria1
     */
    public RegistarEntidades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_InserirEntidade = new javax.swing.JTextField();
        btn_AddCategoria = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_NifEntidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Contacto = new javax.swing.JTextField();
        btn_sair = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Registar Entidades");

        jLabel2.setText("Entidade");

        txt_InserirEntidade.setToolTipText("Indique o nome da categoria a inserir");

        btn_AddCategoria.setText("Gravar");
        btn_AddCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddCategoriaActionPerformed(evt);
            }
        });

        jLabel3.setText("NIF");

        txt_NifEntidade.setToolTipText("Indique o nome da categoria a inserir");
        txt_NifEntidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NifEntidadeActionPerformed(evt);
            }
        });
        txt_NifEntidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NifEntidadeKeyTyped(evt);
            }
        });

        jLabel4.setText("Contacto");

        txt_Contacto.setToolTipText("Indique o nome da categoria a inserir");
        txt_Contacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ContactoKeyTyped(evt);
            }
        });

        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_sair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_AddCategoria))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1)
                                .addGap(0, 142, Short.MAX_VALUE))
                            .addComponent(txt_InserirEntidade)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_NifEntidade, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Contacto)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_InserirEntidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_NifEntidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AddCategoria)
                    .addComponent(btn_sair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddCategoriaActionPerformed
        
        Create createentidade = new Create();
        NoRepeat norepeat = new NoRepeat();
        
        if(txt_InserirEntidade.getText().length()>0){
            createentidade.entidade = txt_InserirEntidade.getText();
            createentidade.nif = Integer.parseInt(txt_NifEntidade.getText());
            createentidade.contacto = txt_Contacto.getText();
            createentidade.estado = true;
            createentidade.codentidade = null;
            
        }else
            JOptionPane.showMessageDialog(null, "Insira uma entidade");
        
        
        norepeat.entidades = txt_InserirEntidade.getText();
        if(norepeat.verifyRepetedEntidades()){
            JOptionPane.showMessageDialog(null,"A Entidade já existe!");
            txt_InserirEntidade.setText(null);
        }else{
            
            if(createentidade.CreateNewEntidade()==true)
            {
                txt_InserirEntidade.setText(null);
                txt_NifEntidade.setText(null);
                txt_Contacto.setText(null);
            //this.dispose();
            }
        }
    }//GEN-LAST:event_btn_AddCategoriaActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sairActionPerformed

    private void txt_NifEntidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NifEntidadeKeyTyped

         if(txt_NifEntidade.getText().length()==9) {  
            evt.consume();
         }

    }//GEN-LAST:event_txt_NifEntidadeKeyTyped

    private void txt_ContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ContactoKeyTyped
        
        if(txt_Contacto.getText().length()==9) {  
            evt.consume();
         }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ContactoKeyTyped

    private void txt_NifEntidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NifEntidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NifEntidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddCategoria;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_Contacto;
    private javax.swing.JTextField txt_InserirEntidade;
    private javax.swing.JTextField txt_NifEntidade;
    // End of variables declaration//GEN-END:variables
}
